//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonimentsWithClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbonimentsWithClient()
        {
            this.CustomerInfo = new HashSet<CustomerInfo>();
        }
    
        public int abonimentClientId { get; set; }
        public Nullable<int> abonimentId { get; set; }
        public Nullable<System.DateTime> selldate { get; set; }
        public Nullable<int> externgroup { get; set; }
    
        public virtual Aboniments Aboniments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInfo> CustomerInfo { get; set; }
    }
}
