//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonimentsWithClient
    {
        public int abonimentClientId { get; set; }
        public Nullable<int> abonimentId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.DateTime> selldate { get; set; }
        public Nullable<int> externgroup { get; set; }
    
        public virtual Aboniments Aboniments { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
