//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aboniments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aboniments()
        {
            this.AbonimentsWithClient = new HashSet<AbonimentsWithClient>();
        }
    
        public int abonimentId { get; set; }
        public string abonimentDescription { get; set; }
        public int abonimentDuration { get; set; }
        public bool poolacsess { get; set; }
        public decimal abonimentCost { get; set; }
        public Nullable<double> abonimentSale { get; set; }
        public Nullable<int> groupCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonimentsWithClient> AbonimentsWithClient { get; set; }
    }
}
