//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int customerInfoId { get; set; }
        public Nullable<int> customerId { get; set; }
        public string city { get; set; }
        public string sex { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string Phone { get; set; }
        public string userimage { get; set; }
        public string detailinfo { get; set; }
        public Nullable<int> abonimentClientId { get; set; }
    
        public virtual AbonimentsWithClient AbonimentsWithClient { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
