//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupLessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupLessons()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int grouplessonId { get; set; }
        public int lessontypeId { get; set; }
        public System.DateTime grouplessondate { get; set; }
        public int lessontimeId { get; set; }
        public Nullable<int> trainerId { get; set; }
        public Nullable<int> SportHallid { get; set; }
    
        public virtual LessonsType LessonsType { get; set; }
        public virtual WorkTimes WorkTimes { get; set; }
        public virtual SportHalls SportHalls { get; set; }
        public virtual TrainerInfo TrainerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
