//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualLesson
    {
        public int IndividualLesson1 { get; set; }
        public int lessontypeId { get; set; }
        public int trainerId { get; set; }
        public int clientid { get; set; }
        public System.DateTime lessondate { get; set; }
        public System.TimeSpan lessontime { get; set; }
        public Nullable<int> SportHallid { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual LessonsType LessonsType { get; set; }
        public virtual SportHalls SportHalls { get; set; }
        public virtual TrainerInfo TrainerInfo { get; set; }
    }
}
